import {useState} from 'react';
import type {CommercialScope} from '../../domain/commercialKernel/types';
import {verifyCommercialProtocol} from '../../domain/commercialKernel/commercialProtocol';
import {receiveCommercialProtocol} from '../../domain/commercialKernel/commercialProtocolCommands';
const field='mt-1 w-full rounded-lg border border-line bg-white px-3 py-2 text-sm';
export function CommercialProtocolIntake({scope}:{scope:CommercialScope}){
 const [text,setText]=useState(''),[recipient,setRecipient]=useState(''),[key,setKey]=useState(''),[checked,setChecked]=useState<Awaited<ReturnType<typeof verifyCommercialProtocol>>|null>(null),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const clear=()=>{setChecked(null);setConfirmed(false);setMessage('');};
 const check=async()=>{clear();setBusy(true);try{const v=await verifyCommercialProtocol(JSON.parse(text),{recipientReference:recipient.trim(),...(key.trim()?{expectedIssuerKeyFingerprint:key.trim()}:{})});if(v.message.sample!==Boolean(scope.sampleDataActive))throw new Error('Protocol sample scope does not match.');setChecked(v);setMessage(v.signatureVerified?'Signature checked. Company identity and commercial truth remain unconfirmed.':'Integrity checked. This unsigned message does not authenticate its issuer.');}catch(error){setMessage(error instanceof Error?error.message:'Protocol check failed.');}finally{setBusy(false);}};
 const receive=async()=>{if(!checked)return;setBusy(true);try{const result=await receiveCommercialProtocol(scope,checked.message,{recipientReference:recipient.trim(),...(key.trim()?{expectedIssuerKeyFingerprint:key.trim()}:{}) ,confirmed});setConfirmed(false);setMessage(result.duplicate?'This exact protocol snapshot was already received as unaccepted claims.':'Protocol snapshot received as unaccepted claims. Your requirements, evidence, money and decisions remain under your control.');}catch(error){setMessage(error instanceof Error?error.message:'Protocol receipt was not confirmed.');}finally{setBusy(false);}};
 return <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-semibold">Receive a commercial protocol message</summary><section aria-label="Commercial protocol intake" className="mt-2 space-y-2"><p className="text-sm text-muted">Check the declared recipient, contents and optional agreed signing key. A successful check allows receipt as claims and grants no authority to change your business state.</p>
  <label className="block text-sm">Protocol recipient reference<input aria-label="Protocol recipient reference" className={field} maxLength={200} disabled={busy} value={recipient} onChange={e=>{setRecipient(e.target.value);clear();}}/></label>
  <label className="block text-sm">Agreed protocol issuer key fingerprint (optional)<input aria-label="Agreed protocol issuer key fingerprint" className={field} maxLength={64} disabled={busy} value={key} onChange={e=>{setKey(e.target.value);clear();}}/></label>
  <label className="block text-sm">Commercial protocol JSON<textarea aria-label="Commercial protocol JSON" className={field} maxLength={20000} disabled={busy} value={text} onChange={e=>{setText(e.target.value);clear();}}/></label><button type="button" className="text-sm text-brand-blue" disabled={busy} onClick={()=>{void check();}}>Check protocol message</button>
  {checked&&<div className="rounded-lg border border-line p-3 text-sm"><p>Declared issuer {checked.message.issuerReference} · {checked.message.body.outcome.statement}. Shared acceptance is unconfirmed.</p><label className="mt-2 flex gap-2"><input type="checkbox" disabled={busy} checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm receipt of this checked protocol snapshot as unaccepted claims.</label><button type="button" className="mt-2 text-brand-blue disabled:opacity-40" disabled={!confirmed||busy} onClick={()=>{void receive();}}>Receive protocol snapshot</button></div>}
  {message&&<p role="status" className="text-sm">{message}</p>}
 </section></details>;
}
