import {useEffect,useState} from 'react';
import type {CommercialScope} from '../../domain/commercialKernel/types';
import {loadOutcomeRequirements} from '../../services/commercialKernel/requirementStore';
import {loadEvents} from '../../services/commercialKernel/eventStore';
import {crossCompanyFederationSources,previewCrossCompanyState,issueCrossCompanyState,receiveCrossCompanyState,type PublicRequirementMapping} from '../../domain/commercialKernel/crossCompanyStateCommands';
import {deriveCrossCompanyState} from '../../domain/commercialKernel/crossCompanyState';
import {exportCommercialProtocol} from '../../domain/commercialKernel/commercialProtocolCommands';
import {CommercialProtocolIntake} from './CommercialProtocolIntake';
const field='mt-1 w-full rounded-lg border border-line bg-white px-3 py-2 text-sm';
export function CrossCompanyStatePanel({scope}:{scope:CommercialScope}){
 const [sources,setSources]=useState<Awaited<ReturnType<typeof crossCompanyFederationSources>>>([]),[sourceId,setSourceId]=useState(''),[opportunity,setOpportunity]=useState(''),[mapping,setMapping]=useState<PublicRequirementMapping[]>([]);
 const [preview,setPreview]=useState<Awaited<ReturnType<typeof previewCrossCompanyState>>|null>(null),[view,setView]=useState<Awaited<ReturnType<typeof deriveCrossCompanyState>>|null>(null),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[text,setText]=useState(''),[recipientRef,setRecipientRef]=useState(''),[receiveConfirmed,setReceiveConfirmed]=useState(false);
 const requirements=loadOutcomeRequirements().filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)&&row.lifecycle==='active'),opportunities=[...new Set(requirements.map(row=>row.opportunityId))],source=sources.find(row=>row.eventId===sourceId);
 const clear=()=>{setPreview(null);setView(null);setConfirmed(false);};
 const refresh=async()=>{setBusy(true);try{setSources(await crossCompanyFederationSources(scope));}catch(error){setSources([]);setMessage(error instanceof Error?error.message:'Federation source unavailable.');}finally{setBusy(false);}};
 useEffect(()=>{let active=true;void crossCompanyFederationSources(scope).then(rows=>{if(active)setSources(rows);}).catch(()=>{if(active)setMessage('Federation sources could not be read.');});return()=>{active=false;};},[scope]);
 const prepare=async()=>{setBusy(true);try{const result=await previewCrossCompanyState(scope,{opportunityId:opportunity,federationEventId:sourceId,mappings:mapping});setPreview(result);setView(await deriveCrossCompanyState(result.state));setConfirmed(false);setMessage('Review the exact requirements, selected prerequisite basis and issuer-local assessments to disclose.');}catch(error){setMessage(error instanceof Error?error.message:'Assessment preview unavailable.');}finally{setBusy(false);}};
 const issue=async()=>{if(!preview)return;setBusy(true);try{await issueCrossCompanyState(scope,{...preview,confirmed});clear();setMessage('Issuer-local assessment issued in this browser. Delivery, counterparty acceptance and shared outcome completion remain unconfirmed.');}catch(error){setMessage(error instanceof Error?error.message:'Assessment issuance was not confirmed.');}finally{setBusy(false);}};
 const receive=async()=>{setBusy(true);try{const result=await receiveCrossCompanyState(scope,JSON.parse(text),recipientRef.trim(),receiveConfirmed);setReceiveConfirmed(false);setView(await deriveCrossCompanyState(JSON.parse(result.event.structuredPayload.rawText as string)));setMessage(result.duplicate?'This exact assessment was already received as an external claim.':'Assessment received as an issuer-local claim. Your own requirements, evidence and decisions were not changed.');}catch(error){setMessage(error instanceof Error?error.message:'Assessment receipt was not confirmed.');}finally{setBusy(false);}};
 const update=(id:string,patch:Partial<PublicRequirementMapping>)=>{setMapping(rows=>rows.map(row=>row.requirementId===id?{...row,...patch}:row));clear();};
 const issued=loadEvents().filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)&&row.eventType==='cross_company_state_issued');
 const download=(value:unknown,filename='memoire-cross-company-assessment.json')=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download=filename;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const protocolDownload=async(id:string)=>{setBusy(true);try{download(await exportCommercialProtocol(scope,id),'memoire-commercial-protocol-v1.json');setMessage('Protocol message downloaded from the issued public assessment. Unsigned integrity only; delivery and shared acceptance remain unconfirmed.');}catch(error){setMessage(error instanceof Error?error.message:'Protocol export unavailable.');}finally{setBusy(false);}};
 return <details className="rounded-panel border border-line bg-white p-4"><summary className="cursor-pointer font-semibold text-ink">Cross-company prerequisites</summary><section aria-label="Cross-company prerequisites" className="mt-3 space-y-3"><p className="text-sm text-muted">Share selected existing prerequisite relationships and your local assessment. Another party’s reported completion remains its claim; each company controls its own accepted evidence and decisions.</p><button type="button" disabled={busy} onClick={()=>{void refresh();}} className="text-sm text-brand-blue">Refresh shared assessment sources</button>
  <label className="block text-sm">Federation source<select aria-label="Cross-company federation source" className={field} value={sourceId} disabled={busy} onChange={e=>{setSourceId(e.target.value);setMapping([]);clear();}}><option value="">Choose an issued or received exchange</option>{sources.map(row=><option key={row.eventId} value={row.eventId}>{row.exchange.thread.reference} · {row.exchange.issuer.label}</option>)}</select></label>
  <label className="block text-sm">Opportunity requirement set<select aria-label="Opportunity requirement set" className={field} value={opportunity} disabled={busy} onChange={e=>{setOpportunity(e.target.value);setMapping([]);clear();}}><option value="">Choose existing requirements</option>{opportunities.map(id=><option key={id} value={id}>{requirements.find(row=>row.opportunityId===id)?.expectedOutcome}</option>)}</select></label><p className="text-xs text-muted">Record requirements and prerequisites in Opportunity first. This exchange reads that existing graph.</p>
  {requirements.filter(row=>row.opportunityId===opportunity).map(row=>{const alias=mapping.find(item=>item.requirementId===row.id);return <div key={row.id} className="rounded-lg border border-line p-3"><label className="flex gap-2 text-sm"><input type="checkbox" disabled={busy||!source} checked={!!alias} onChange={e=>{setMapping(rows=>e.target.checked?[...rows,{requirementId:row.id,reference:'',partyReference:source?.exchange.issuer.reference||'',commitmentRef:null}]:rows.filter(item=>item.requirementId!==row.id));clear();}}/>{row.expectedOutcome}</label>{alias&&<div className="mt-2 space-y-2"><label className="block text-sm">Public requirement reference<input aria-label={'Public requirement reference '+row.expectedOutcome} className={field} maxLength={200} disabled={busy} value={alias.reference} onChange={e=>update(row.id,{reference:e.target.value.trim()})}/></label><label className="block text-sm">Declared responsible party<select aria-label={'Responsible party '+row.expectedOutcome} className={field} disabled={busy} value={alias.partyReference} onChange={e=>update(row.id,{partyReference:e.target.value,commitmentRef:null})}><option value={source?.exchange.issuer.reference}>{source?.exchange.issuer.label}</option><option value={source?.exchange.recipient.reference}>{source?.exchange.recipient.label}</option></select></label><label className="block text-sm">Selected reported promise (optional)<select aria-label={'Reported promise '+row.expectedOutcome} className={field} disabled={busy} value={alias.commitmentRef||''} onChange={e=>update(row.id,{commitmentRef:e.target.value||null})}><option value="">No shared promise reference</option>{[...new Set(source?.exchange.capsules.filter(capsule=>capsule.statement.issuer.reference===alias.partyReference).map(capsule=>capsule.statement.commitmentRef)||[])].map(ref=><option key={ref} value={ref}>{ref}</option>)}</select></label></div>}</div>;})}
  <button type="button" disabled={busy} className="text-sm text-brand-blue" onClick={()=>{void prepare();}}>Preview shared prerequisites</button>
  {preview&&<div className="rounded-lg border border-line p-3"><pre aria-label="Cross-company assessment preview" className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(preview.state,null,2)}</pre><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm the exact public requirements, prerequisite basis and my local assessments.</label><button type="button" disabled={!confirmed||busy} className="mt-3 text-sm text-brand-blue disabled:opacity-40" onClick={()=>{void issue();}}>Issue shared assessment</button></div>}
  {issued.slice(0,20).map(row=><div key={row.id} className="text-sm">Issuer-local assessment · {row.recordedAt.slice(0,10)} <button type="button" className="ml-3 text-brand-blue" onClick={()=>download(row.structuredPayload)}>Download shared assessment</button><button type="button" disabled={busy} className="ml-3 text-brand-blue" onClick={()=>{void protocolDownload(row.id);}}>Download protocol message</button></div>)}
  <CommercialProtocolIntake key={JSON.stringify([scope.userId,Boolean(scope.sampleDataActive)])} scope={scope}/>
  <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-semibold">Receive a shared assessment</summary><label className="mt-2 block text-sm">Assessment recipient reference<input aria-label="Assessment recipient reference" className={field} maxLength={200} value={recipientRef} onChange={e=>{setRecipientRef(e.target.value);setReceiveConfirmed(false);}}/></label><label className="mt-2 block text-sm">Shared assessment JSON<textarea aria-label="Shared assessment JSON" className={field} maxLength={20000} value={text} onChange={e=>{setText(e.target.value);setReceiveConfirmed(false);setView(null);}}/></label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={receiveConfirmed} onChange={e=>setReceiveConfirmed(e.target.checked)}/>I confirm receipt of an issuer-local assessment as external claims.</label><button type="button" disabled={!receiveConfirmed||busy} className="mt-2 text-sm text-brand-blue disabled:opacity-40" onClick={()=>{void receive();}}>Receive shared assessment</button></details>
  {view&&<div className="rounded-lg border border-line p-3 text-sm"><p>Assessed by declared party {view.assessedBy}. Shared outcome completion is unconfirmed.</p>{view.dependencies.map(edge=><p key={edge.dependentReference+edge.prerequisiteReference} className="mt-2">{edge.dependentReference} requires {edge.prerequisiteReference} · issuer assessment {edge.prerequisiteLocalAssessment} · reported promise {edge.reportedPromiseStatuses.join(', ')||'unknown'}{edge.independentVerificationNeeded?' · independent verification needed':''}</p>)}</div>}{message&&<p role="status" className="text-sm">{message}</p>}
 </section></details>;
}
