import {useState} from 'react';
import type {CommercialScope,CommercialCommitment} from '../../domain/commercialKernel/types';
import {normalizeSharedCommitment,previewSharedCommitment,type SharedCommitmentStatement} from '../../domain/commercialKernel/sharedCommitment';
import {issueSharedCommitment,receiveSharedCommitment} from '../../domain/commercialKernel/sharedCommitmentCommands';
import {loadEvents} from '../../services/commercialKernel/eventStore';
import {createTrustCapsule,verifyTrustCapsule} from '../../domain/commercialKernel/trustCapsule';
import {receiveTrustCapsule} from '../../domain/commercialKernel/trustCapsuleCommands';
const field='mt-1 w-full rounded-lg border border-line bg-white px-3 py-2 text-sm';
export function ExternalPromisesPanel({scope,commitments}:{scope:CommercialScope;commitments:CommercialCommitment[]}){
 const [selected,setSelected]=useState(''),[issuerRef,setIssuerRef]=useState(''),[issuerLabel,setIssuerLabel]=useState(''),[recipientRef,setRecipientRef]=useState(''),[recipientLabel,setRecipientLabel]=useState(''),[reference,setReference]=useState(''),[evidence,setEvidence]=useState(false);
 const [preview,setPreview]=useState<SharedCommitmentStatement|null>(null),[confirmed,setConfirmed]=useState(false),[message,setMessage]=useState(''),[importText,setImportText]=useState(''),[receiveConfirmed,setReceiveConfirmed]=useState(false),[busy,setBusy]=useState(false);
 const [capsuleText,setCapsuleText]=useState(''),[expectedKey,setExpectedKey]=useState(''),[capsuleConfirmed,setCapsuleConfirmed]=useState(false),[checkedCapsule,setCheckedCapsule]=useState<Awaited<ReturnType<typeof verifyTrustCapsule>>|null>(null);
 const [issued,setIssued]=useState(()=>loadEvents().filter(row=>row.eventType==='shared_commitment_issued'&&row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)));
 const clear=()=>{setPreview(null);setConfirmed(false);};
 const prepare=()=>{try{const promise=commitments.find(row=>row.id===selected);if(!promise)throw new Error('Choose your promise to disclose.');setPreview(previewSharedCommitment(scope,promise,{issuer:{reference:issuerRef.trim(),label:issuerLabel.trim()},recipient:{reference:recipientRef.trim(),label:recipientLabel.trim()},commitmentRef:reference.trim(),includeCompletionEvidence:evidence}));setConfirmed(false);setMessage('Review the exact statement before issuing it. Party references and labels are your declarations.');}catch(error){setMessage(error instanceof Error?error.message:'Preview unavailable.');}};
 const issue=()=>{if(!preview)return;try{issueSharedCommitment(scope,selected,preview,confirmed);setIssued(loadEvents().filter(row=>row.eventType==='shared_commitment_issued'&&row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)));clear();setMessage('Statement issued and saved in this browser. Download it to share through your chosen channel; delivery and recipient acceptance have not been confirmed.');}catch(error){setMessage(error instanceof Error?error.message:'Statement was not saved.');}};
 const download=(value:unknown)=>{const statement=normalizeSharedCommitment(value),url=URL.createObjectURL(new Blob([JSON.stringify(statement,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='memoire-promise-'+statement.statementId+'.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const downloadCapsule=async(value:unknown)=>{try{const capsule=await createTrustCapsule(value),url=URL.createObjectURL(new Blob([JSON.stringify(capsule,null,2)],{type:'application/json'}));const anchor=document.createElement('a');anchor.href=url;anchor.download='memoire-capsule-'+capsule.statement.statementId+'.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Integrity capsule produced. It is unsigned and does not authenticate the issuing organization.');}catch(error){setMessage(error instanceof Error?error.message:'Capsule unavailable.');}};
 const checkCapsule=async()=>{setBusy(true);setCheckedCapsule(null);setCapsuleConfirmed(false);try{setCheckedCapsule(await verifyTrustCapsule(JSON.parse(capsuleText),{expectedRecipientReference:recipientRef.trim(),...(expectedKey.trim()?{expectedIssuerKeyFingerprint:expectedKey.trim()}:{})}));setMessage('Capsule integrity checked. Review the signature and party scope before receiving its claim.');}catch(error){setMessage(error instanceof Error?error.message:'Capsule verification failed.');}finally{setBusy(false);}};
 const receiveCapsule=async()=>{if(!checkedCapsule)return;setBusy(true);try{const result=await receiveTrustCapsule(scope,checkedCapsule.capsule,{recipientReference:recipientRef.trim(),expectedIssuerKeyFingerprint:expectedKey.trim()||undefined,confirmed:capsuleConfirmed});setCapsuleConfirmed(false);setMessage(result.duplicate?'This exact capsule was already received as an unaccepted claim.':'Checked capsule received as an unaccepted claim. Canonical commercial state was not changed.');}catch(error){setMessage(error instanceof Error?error.message:'Capsule receipt could not be confirmed.');}finally{setBusy(false);}};
 const receive=async()=>{setBusy(true);try{const result=await receiveSharedCommitment(scope,JSON.parse(importText),recipientRef.trim(),receiveConfirmed);setReceiveConfirmed(false);setMessage(result.duplicate?'This exact statement was already received. It remains an unaccepted source claim.':'Statement received as an unaccepted source claim. Your promises, evidence and decisions have not changed.');}catch(error){setMessage(error instanceof Error?error.message:'Statement receipt could not be confirmed.');}finally{setBusy(false);}};
 return <details className="rounded-panel border border-line bg-white p-4"><summary className="cursor-pointer font-semibold text-ink">External promise statements</summary><section aria-label="External promise statements" className="mt-3 space-y-3">
  <p className="text-sm text-muted">Issue a deliberately selected statement for another party. Each party keeps its own records and decides what it accepts. Party names and references are declarations; completion evidence is the issuer’s selected assertion.</p>
  <label className="block text-sm">Promise to disclose<select aria-label="Promise to disclose" className={field} value={selected} onChange={e=>{setSelected(e.target.value);clear();}}><option value="">Choose your promise</option>{commitments.filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)).map(row=><option key={row.id} value={row.id}>{row.commitmentText}</option>)}</select></label>
  <div className="grid gap-3 sm:grid-cols-2">{[['Issuing party reference',issuerRef,setIssuerRef],['Issuing party name',issuerLabel,setIssuerLabel],['Recipient party reference',recipientRef,setRecipientRef],['Recipient party name',recipientLabel,setRecipientLabel],['Public promise reference',reference,setReference]].map(([label,value,setter])=><label key={String(label)} className="block text-sm">{String(label)}<input aria-label={String(label)} className={field} maxLength={200} value={String(value)} onChange={e=>{(setter as (value:string)=>void)(e.target.value);clear();setReceiveConfirmed(false);setCheckedCapsule(null);setCapsuleConfirmed(false);}}/></label>)}</div>
  <label className="flex gap-2 text-sm"><input type="checkbox" checked={evidence} onChange={e=>{setEvidence(e.target.checked);clear();}}/>Include the existing completion evidence text, if this promise is completed.</label>
  <button type="button" className="text-sm font-semibold text-brand-blue" onClick={prepare}>Preview external statement</button>
  {preview&&<div className="rounded-lg border border-line p-3"><pre aria-label="Statement preview" className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(preview,null,2)}</pre><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm these parties and the exact promise and evidence to disclose.</label><button type="button" disabled={!confirmed} onClick={issue} className="mt-3 rounded-full bg-brand-blue px-3 py-2 text-sm text-white disabled:opacity-40">Issue statement</button></div>}
  {issued.slice(0,20).map(row=><div key={row.id} className="rounded-lg border border-line p-3 text-sm"><span>Issued {row.recordedAt.slice(0,10)} · {String(row.structuredPayload.commitmentRef)}</span><button type="button" className="ml-3 text-brand-blue" onClick={()=>download(row.structuredPayload)}>Download statement</button><button type="button" className="ml-3 text-brand-blue" onClick={()=>{void downloadCapsule(row.structuredPayload);}}>Download integrity capsule</button></div>)}
  <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-semibold">Receive an external statement</summary><p className="mt-2 text-xs text-muted">Use the recipient reference agreed between parties. A matching reference does not authenticate the issuer or prove the source claim.</p><label className="mt-2 block text-sm">Statement JSON<textarea aria-label="Statement JSON" className={field} maxLength={20000} value={importText} onChange={e=>{setImportText(e.target.value);setReceiveConfirmed(false);}}/></label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={receiveConfirmed} onChange={e=>setReceiveConfirmed(e.target.checked)}/>I confirm receipt as an unaccepted source claim.</label><button type="button" disabled={!receiveConfirmed||busy} className="mt-2 text-sm text-brand-blue disabled:opacity-40" onClick={()=>{void receive();}}>Receive statement</button></details>
  <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-semibold">Check a trust capsule</summary><p className="mt-2 text-xs text-muted">Integrity checks detect changed content. A signature can match a signing key agreed through another channel; company identity and commercial truth still need your own verification.</p><label className="mt-2 block text-sm">Capsule JSON<textarea aria-label="Capsule JSON" className={field} maxLength={20000} value={capsuleText} onChange={e=>{setCapsuleText(e.target.value);setCheckedCapsule(null);setCapsuleConfirmed(false);}}/></label><label className="mt-2 block text-sm">Agreed issuer key fingerprint (optional)<input aria-label="Agreed issuer key fingerprint" className={field} maxLength={64} value={expectedKey} onChange={e=>{setExpectedKey(e.target.value);setCheckedCapsule(null);setCapsuleConfirmed(false);}}/></label><button type="button" disabled={busy} onClick={()=>{void checkCapsule();}} className="mt-2 text-sm text-brand-blue">Check capsule integrity</button>
   {checkedCapsule&&<div className="mt-3 space-y-2 text-sm"><p>Integrity verified · {checkedCapsule.signatureVerified?'signature verified':'unsigned'} · {checkedCapsule.configuredIssuerKeyMatched?'agreed signing key matched':'issuer key not independently agreed'}</p><p>Issuer: {checkedCapsule.capsule.statement.issuer.label} · Recipient: {checkedCapsule.capsule.statement.recipient.label} · {checkedCapsule.capsule.statement.promise.text}</p><label className="flex gap-2"><input type="checkbox" checked={capsuleConfirmed} onChange={e=>setCapsuleConfirmed(e.target.checked)}/>I confirm receipt of this checked capsule as an unaccepted claim.</label><button type="button" disabled={!capsuleConfirmed||busy} className="text-brand-blue disabled:opacity-40" onClick={()=>{void receiveCapsule();}}>Receive checked capsule</button></div>}
  </details>
  {scope.sampleDataActive&&<p className="text-xs text-muted">Statements are marked as sample and can be received only in sample mode.</p>}
  {message&&<p role="status" className="text-sm">{message}</p>}
 </section></details>;
}
