import {useEffect,useState} from 'react';
import type {CommercialScope,CommercialThread} from '../../domain/commercialKernel/types';
import {loadThreads} from '../../services/commercialKernel/threadStore';
import {loadEvents} from '../../services/commercialKernel/eventStore';
import {availableFederationCapsules,previewFederatedThread,issueFederatedThread,receiveFederatedThread} from '../../domain/commercialKernel/federatedThreadCommands';
import {deriveFederatedThreads} from '../../domain/commercialKernel/federatedThread';
const field='mt-1 w-full rounded-lg border border-line bg-white px-3 py-2 text-sm';
export function FederatedThreadsPanel({scope}:{scope:CommercialScope}){
 const [threads,setThreads]=useState<CommercialThread[]>(()=>loadThreads().filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive))),[sources,setSources]=useState<Awaited<ReturnType<typeof availableFederationCapsules>>>([]),[groups,setGroups]=useState<Awaited<ReturnType<typeof deriveFederatedThreads>>|null>(null);
 const [threadId,setThreadId]=useState(''),[reference,setReference]=useState(''),[objective,setObjective]=useState(''),[issuerRef,setIssuerRef]=useState(''),[issuerName,setIssuerName]=useState(''),[recipientRef,setRecipientRef]=useState(''),[recipientName,setRecipientName]=useState(''),[ids,setIds]=useState<string[]>([]);
 const [preview,setPreview]=useState<(Awaited<ReturnType<typeof previewFederatedThread>>&{threadId:string})|null>(null),[confirmed,setConfirmed]=useState(false),[text,setText]=useState(''),[receiveConfirmed,setReceiveConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const clear=()=>{setPreview(null);setConfirmed(false);};
 const refresh=async()=>{setBusy(true);try{setThreads(loadThreads().filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)));setSources(await availableFederationCapsules(scope));setGroups(await deriveFederatedThreads(scope,loadEvents(),new Date().toISOString()));}catch(error){setSources([]);setGroups(null);setMessage(error instanceof Error?error.message:'Federation sources unavailable.');}finally{setBusy(false);}};
 useEffect(()=>{let active=true;void availableFederationCapsules(scope).then(rows=>{if(active)setSources(rows);}).catch(()=>{if(active)setMessage('Federation sources could not be read. Preserve a backup.');});return()=>{active=false;};},[scope]);
 const prepare=async()=>{setBusy(true);try{const result=await previewFederatedThread(scope,{threadId,reference:reference.trim(),objective:objective.trim(),issuer:{reference:issuerRef.trim(),label:issuerName.trim()},recipient:{reference:recipientRef.trim(),label:recipientName.trim()},eventIds:ids});setPreview({...result,threadId});setConfirmed(false);setMessage('Review this exact public outcome and selected attributed claims.');}catch(error){setMessage(error instanceof Error?error.message:'Exchange preview unavailable.');}finally{setBusy(false);}};
 const issue=async()=>{if(!preview)return;setBusy(true);try{await issueFederatedThread(scope,{...preview,confirmed});clear();setMessage('Exchange issued in this browser. Download and transmit it through your chosen channel; recipient acceptance is unconfirmed.');setGroups(await deriveFederatedThreads(scope,loadEvents(),new Date().toISOString()));}catch(error){setMessage(error instanceof Error?error.message:'Exchange issuance was not confirmed.');}finally{setBusy(false);}};
 const receive=async()=>{setBusy(true);try{const result=await receiveFederatedThread(scope,JSON.parse(text),recipientRef.trim(),receiveConfirmed);setReceiveConfirmed(false);setMessage(result.duplicate?'This exact exchange was already received as external claims.':'Exchange received as external claims. Your local thread and canonical commercial state were not changed.');setGroups(await deriveFederatedThreads(scope,loadEvents(),new Date().toISOString()));}catch(error){setMessage(error instanceof Error?error.message:'Exchange receipt was not confirmed.');}finally{setBusy(false);}};
 const download=(value:unknown)=>{const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'})),anchor=document.createElement('a');anchor.href=url;anchor.download='memoire-federated-thread.json';anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const issued=loadEvents().filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive)&&row.eventType==='federated_thread_issued');
 return <details className="rounded-panel border border-line bg-white p-4"><summary className="cursor-pointer font-semibold text-ink">Federated threads</summary><section aria-label="Federated threads" className="mt-3 space-y-3">
  <p className="text-sm text-muted">Connect your local story to a public thread reference agreed with another party. Exchange only selected promise capsules. Each party keeps its own internal state and authority.</p><button type="button" disabled={busy} onClick={()=>{void refresh();}} className="text-sm text-brand-blue">Refresh federation sources</button>
  <label className="block text-sm">Local thread<select aria-label="Federation local thread" className={field} disabled={busy} value={threadId} onChange={e=>{setThreadId(e.target.value);clear();}}><option value="">Choose a saved canonical thread</option>{threads.map(row=><option key={row.id} value={row.id}>{row.title}</option>)}</select></label>
  {([['Public thread reference',reference,setReference],['Public shared outcome',objective,setObjective],['Federation issuing party reference',issuerRef,setIssuerRef],['Federation issuing party name',issuerName,setIssuerName],['Federation recipient reference',recipientRef,setRecipientRef],['Federation recipient name',recipientName,setRecipientName]] as const).map(([label,value,setter])=><label key={label} className="block text-sm">{label}<input aria-label={label} className={field} maxLength={label==='Public shared outcome'?1000:200} disabled={busy} value={value} onChange={e=>{setter(e.target.value);clear();setReceiveConfirmed(false);}}/></label>)}
  <p className="text-sm font-semibold">Selected statements already issued or received in this workspace</p>{sources.map(source=><label key={source.eventId} className="flex gap-2 text-sm"><input type="checkbox" disabled={busy} checked={ids.includes(source.eventId)} onChange={e=>{setIds(rows=>e.target.checked?[...rows,source.eventId]:rows.filter(id=>id!==source.eventId));clear();}}/>{source.capsule.statement.commitmentRef} · {source.capsule.statement.promise.text} · declared by {source.capsule.statement.issuer.label}</label>)}
  <button type="button" disabled={busy} className="text-sm text-brand-blue" onClick={()=>{void prepare();}}>Preview federated exchange</button>
  {preview&&<div className="rounded-lg border border-line p-3"><pre aria-label="Federated exchange preview" className="whitespace-pre-wrap break-all text-xs">{JSON.stringify(preview.exchange,null,2)}</pre><label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I confirm the public outcome, parties and exact selected claims.</label><button type="button" disabled={!confirmed||busy} className="mt-3 text-sm text-brand-blue disabled:opacity-40" onClick={()=>{void issue();}}>Issue federated exchange</button></div>}
  {issued.slice(0,20).map(row=><div key={row.id} className="text-sm">{String((row.structuredPayload.thread as {reference?:string})?.reference)} <button type="button" className="ml-3 text-brand-blue" onClick={()=>download(row.structuredPayload)}>Download federated exchange</button></div>)}
  <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-semibold">Receive a federated exchange</summary><label className="mt-2 block text-sm">Federated exchange JSON<textarea aria-label="Federated exchange JSON" className={field} maxLength={20000} value={text} onChange={e=>{setText(e.target.value);setReceiveConfirmed(false);}}/></label><label className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={receiveConfirmed} onChange={e=>setReceiveConfirmed(e.target.checked)}/>I confirm receipt of attributed external thread claims.</label><button type="button" disabled={!receiveConfirmed||busy} className="mt-2 text-sm text-brand-blue disabled:opacity-40" onClick={()=>{void receive();}}>Receive federated exchange</button></details>
  {groups?.groups.map((group,index)=><div key={index} className="rounded-lg border border-line p-3 text-sm"><p>{group.reference} · {group.exchanges.length} attributed exchanges · acceptance remains with each party</p>{group.objectiveDisagreement&&<p>Reported outcomes differ; no shared outcome is inferred.</p>}{group.statementIdentityConflict&&<p>Statement identity conflict requires review.</p>}{group.exchanges.map(item=><p key={item.eventId}>{item.exchange.issuer.label}: {item.exchange.thread.objective} · known here {item.recordedAt.slice(0,10)}</p>)}</div>)}
  {!!groups?.rejectedEventIds.length&&<p className="text-sm">Some stored exchanges failed verification. This reading is incomplete.</p>}{message&&<p role="status" className="text-sm">{message}</p>}
 </section></details>;
}
