import {useEffect,useState} from 'react';
import type {CommercialScope,CommercialCommitment} from '../../domain/commercialKernel/types';
import type {CommercialWorkspace,WorkspaceMember} from '../../domain/commercialKernel/commercialWorkspace';
import {configureCommercialWorkspace} from '../../domain/commercialKernel/commercialWorkspaceCommands';
import {loadCommercialWorkspaces,loadCommercialWorkspacesForOwner} from '../../services/commercialKernel/commercialWorkspaceStore';
import {listWorkspaceInvitations,readSharedWorkspace,respondSharedWorkspace,type WorkspaceInvitation,type SharedWorkspaceView} from '../../services/commercialKernel/sharedWorkspaceAccess';
const field='mt-1 block w-full rounded-lg border border-line p-2 text-sm';
export function SharedWorkspacesPanel({scope,commitments}:{scope:CommercialScope;commitments:CommercialCommitment[]}){
 const [owned,setOwned]=useState<CommercialWorkspace[]>([]),[editing,setEditing]=useState<CommercialWorkspace|null>(null),[name,setName]=useState(''),[members,setMembers]=useState<WorkspaceMember[]>([]),[ids,setIds]=useState<string[]>([]),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[actor,setActor]=useState(''),[role,setRole]=useState<WorkspaceMember['role']>('reader');
 const [message,setMessage]=useState(''),[invitations,setInvitations]=useState<WorkspaceInvitation[]>([]),[reading,setReading]=useState<SharedWorkspaceView|null>(null),[review,setReview]=useState(''),[reviewId,setReviewId]=useState(''),[busy,setBusy]=useState(false);
 const connected=Boolean(scope.userId)&&!scope.sampleDataActive;
 const ownedPromises=commitments.filter(row=>row.userId===scope.userId&&Boolean(row.isSample)===Boolean(scope.sampleDataActive));
 useEffect(()=>{let active=true;void loadCommercialWorkspacesForOwner(scope.userId,scope.sampleDataActive).then(rows=>{if(active)setOwned(rows);}).catch(()=>{if(active)setMessage('Workspace configuration could not be refreshed. Keep your browser backup and retry.');});return()=>{active=false;};},[scope.userId,scope.sampleDataActive]);
 const edit=(row:CommercialWorkspace|null)=>{setEditing(row);setName(row?.name||'');setMembers(row?.members||[]);setIds(row?.commitmentIds||[]);setReason('');setConfirmed(false);};
 const save=(lifecycle:'active'|'retired')=>{try{const row=configureCommercialWorkspace(scope,{id:editing?.id,expectedVersion:editing?.version,name,members,commitmentIds:ids,revisionReason:reason,lifecycle,confirmed},commitments);setOwned(loadCommercialWorkspaces().filter(record=>record.userId===scope.userId&&Boolean(record.isSample)===Boolean(scope.sampleDataActive)));edit(row);setMessage('Configuration saved in this browser. Access changes take effect only after account synchronization. Members must accept new or changed invitations.');}catch(error){setMessage(error instanceof Error?error.message:'Workspace could not be saved.');}};
 const refresh=async()=>{setBusy(true);setReading(null);try{setInvitations(await listWorkspaceInvitations());setMessage('Shared access refreshed from the account. Up to 50 workspaces are shown.');}catch(error){setInvitations([]);setMessage(error instanceof Error?error.message:'Shared access unavailable.');}finally{setBusy(false);}};
 const respond=async(invitation:WorkspaceInvitation,response:'accepted'|'declined')=>{setBusy(true);setReading(null);try{await respondSharedWorkspace(invitation,crypto.randomUUID(),response);setInvitations(await listWorkspaceInvitations());if(response==='accepted')setReading(await readSharedWorkspace(invitation));setMessage(response==='accepted'?'Invitation accepted by your account.':'Access declined by your account.');}catch(error){setMessage(error instanceof Error?error.message:'Response could not be confirmed.');}finally{setBusy(false);}};
 const open=async(invitation:WorkspaceInvitation)=>{setBusy(true);setReading(null);try{setReading(await readSharedWorkspace(invitation));setReview('');setReviewId('');}catch(error){setMessage(error instanceof Error?error.message:'Workspace could not be opened.');}finally{setBusy(false);}};
 const submitReview=async()=>{if(!reading)return;setBusy(true);try{await respondSharedWorkspace(reading,crypto.randomUUID(),'review',reviewId,review);setReading(await readSharedWorkspace(reading));setReview('');setMessage('Review recorded. The owner’s promise and commercial state were not changed.');}catch(error){setReading(null);setMessage(error instanceof Error?error.message:'Review could not be confirmed.');}finally{setBusy(false);}};
 return <details className="rounded-panel border border-line bg-white p-4"><summary className="cursor-pointer font-semibold text-ink">Shared workspaces</summary><section aria-label="Shared workspaces" className="mt-3 space-y-3">
  <p className="text-sm text-muted">Share a live view of selected promises with named account holders. Other records, private notes and supporting evidence remain private. Members accept access themselves; reviewers can add notes, not change your promises.</p>
  {scope.userId&&<p className="break-all text-xs text-muted">Your account reference: {scope.userId}</p>}
  <details className="rounded-lg border border-line p-3"><summary className="cursor-pointer text-sm font-semibold">Manage sharing</summary>
   <label className="mt-3 block text-sm">Owned workspace<select aria-label="Owned workspace" className={field} value={editing?.id||''} onChange={event=>edit(owned.find(row=>row.id===event.target.value)||null)}><option value="">New shared workspace</option>{owned.map(row=><option key={row.id} value={row.id}>{row.name} · {row.lifecycle}</option>)}</select></label>
   <label className="mt-3 block text-sm">Workspace name<input aria-label="Workspace name" className={field} maxLength={200} value={name} onChange={event=>{setName(event.target.value);setConfirmed(false);}}/></label>
   <label className="mt-3 block text-sm">Member account reference<input aria-label="Member account reference" className={field} value={actor} onChange={event=>setActor(event.target.value)}/></label>
   <label className="mt-3 block text-sm">Member access<select aria-label="Member access" className={field} value={role} onChange={event=>setRole(event.target.value as WorkspaceMember['role'])}><option value="reader">Can view</option><option value="reviewer">Can review</option></select></label>
   <button type="button" className="mt-2 text-sm text-brand-blue" onClick={()=>{setMembers(current=>[...current,{actorId:actor.trim(),role}]);setActor('');setConfirmed(false);}}>Add member to preview</button>
   <ul className="mt-2 space-y-2">{members.map((member,index)=><li key={index} className="break-all text-xs">{member.actorId} · {member.role} <button type="button" className="text-brand-blue" onClick={()=>{setMembers(current=>current.filter((_,i)=>i!==index));setConfirmed(false);}}>Remove</button></li>)}</ul>
   <p className="mt-3 text-sm font-semibold">Promises to share</p>{ownedPromises.map(promise=><label key={promise.id} className="mt-2 flex gap-2 text-sm"><input type="checkbox" checked={ids.includes(promise.id)} onChange={event=>{setIds(current=>event.target.checked?[...current,promise.id]:current.filter(id=>id!==promise.id));setConfirmed(false);}}/>{promise.commitmentText} · {promise.ownerLabel||'No responsible person recorded'}</label>)}
   <p className="mt-2 text-xs text-muted">Members see only promise text, responsible person, due date, status and revision time for these selected records.</p>
   <label className="mt-3 block text-sm">Reason for sharing change<input aria-label="Reason for sharing change" className={field} maxLength={1000} value={reason} onChange={event=>setReason(event.target.value)}/></label>
   <label className="mt-3 flex gap-2 text-sm"><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I confirm these people, permissions and exact promises to share.</label>
   <div className="mt-3 flex gap-3"><button type="button" disabled={!confirmed} className="rounded-lg bg-brand-blue px-3 py-2 text-sm text-white disabled:opacity-40" onClick={()=>save('active')}>Save sharing configuration</button>{editing?.lifecycle==='active'&&<button type="button" disabled={!confirmed} className="text-sm text-brand-blue disabled:opacity-40" onClick={()=>save('retired')}>Retire shared workspace</button>}</div>
   {!connected&&<p className="mt-2 text-xs text-muted">This is a local configuration only. Real invitations and shared access require a connected personal account; sample workspaces never share data.</p>}
  </details>
  <button type="button" disabled={!connected||busy} className="text-sm font-semibold text-brand-blue disabled:opacity-40" onClick={()=>{void refresh();}}>Refresh shared access</button>
  {invitations.map(invitation=><div key={invitation.ownerId+':'+invitation.workspaceId} className="rounded-lg border border-line p-3 text-sm"><p>{invitation.name} · {invitation.role} · {invitation.accepted?'accepted':'invitation pending'}</p><div className="mt-2 flex gap-3">
   {invitation.accepted?<button type="button" disabled={busy} onClick={()=>{void open(invitation);}} className="text-brand-blue">Open shared view</button>:<button type="button" disabled={busy} onClick={()=>{void respond(invitation,'accepted');}} className="text-brand-blue">Accept invitation</button>}
   {invitation.role!=='owner'&&<button type="button" disabled={busy} onClick={()=>{void respond(invitation,'declined');}} className="text-brand-blue">Decline access</button>}</div></div>)}
  {reading&&<section aria-label="Shared promise view" className="rounded-lg border border-line p-3"><p className="font-semibold">{reading.name}</p><p className="text-xs text-muted">Account view at last refresh. Review notes are not accepted Evidence or Decisions.</p>
   {reading.commitments.map(promise=><p key={promise.id} className="mt-2 text-sm">{promise.promise} · {promise.responsiblePerson||'No person recorded'} · {promise.dueDate||'No due date'} · {promise.status}</p>)}
   {reading.reviews.map(note=><p key={note.id} className="mt-2 break-words text-sm">Review: {note.review}</p>)}
   {reading.role!=='reader'&&<div className="mt-3 space-y-2"><label className="block text-sm">Promise to review<select aria-label="Promise to review" className={field} value={reviewId} onChange={event=>setReviewId(event.target.value)}><option value="">Choose a shared promise</option>{reading.commitments.map(promise=><option key={promise.id} value={promise.id}>{promise.promise}</option>)}</select></label>
    <label className="block text-sm">Review note<textarea aria-label="Review note" className={field} maxLength={1000} value={review} onChange={event=>setReview(event.target.value)}/></label><button type="button" disabled={busy||!reviewId||!review.trim()} className="text-sm text-brand-blue disabled:opacity-40" onClick={()=>{void submitReview();}}>Record shared review</button></div>}
  </section>}
  {message&&<p role="status" className="text-sm">{message}</p>}
 </section></details>;
}
