import type { ObjectionRecord } from '../services/objectionStore.ts';
import type { OpportunityOutcomeRecord } from '../services/opportunityOutcomeStore.ts';
import type { CrmLiteOpportunity } from '../services/opportunityStore.ts';
import type { SalesActivityRecord } from '../services/salesActivityStore.ts';
import { buildFollowUpImpact, followUpImpactStatusLabel } from './followUpImpact.ts';
import { buildForecastCalibration, formatWinRate } from './forecastCalibration.ts';
import { buildObjectionPlaybook, formatObjectionResolutionRate } from './objectionPlaybook.ts';
import { analyzePersonalSalesLearning } from './personalSalesLearning.ts';
import { formatBaseCurrencyAmount } from './money.ts';

type LearningBriefInput = {
  objections: ObjectionRecord[];
  opportunityOutcomes: OpportunityOutcomeRecord[];
  opportunities: CrmLiteOpportunity[];
  activities: SalesActivityRecord[];
  periodLabel: string;
  today?: string;
};

/**
 * The Commercial Learning Brief (direction 7.5): one copyable answer to
 * "what has my own history taught me?". Composed entirely from the measured
 * layers - forecast calibration, silence ROI, objection playbook, outcome
 * patterns. Every section states plainly when its data is too thin to
 * trust; nothing here is generated by AI or extrapolated beyond evidence.
 */
export function generateCommercialLearningBriefMarkdown(input: LearningBriefInput): string {
  const lines: string[] = [
    `# Commercial Learning Brief - ${input.periodLabel}`,
    '',
    '> Built from measured history only (closed outcomes, logged follow-ups, resolved objections). Sections say so when the data is still too thin to trust.',
    '',
  ];

  // Forecast calibration
  const calibration = buildForecastCalibration({ outcomes: input.opportunityOutcomes, opportunities: input.opportunities });
  lines.push('## Forecast calibration');
  lines.push('');
  if (calibration.totalClosed === 0) {
    lines.push('- No closed outcomes yet - no win-rate history to learn from.');
  } else {
    lines.push(`- ${calibration.headline}`);
    calibration.rows
      .filter((row) => row.sufficientSample && row.winRate !== null)
      .forEach((row) => {
        lines.push(`- ${row.category}: ${formatWinRate(row.winRate)} (${row.won} won / ${row.lost} lost / ${row.stalled} stalled)`);
      });
    calibration.warnings.slice(1).forEach((warning) => lines.push(`- Warning: ${warning.message}`));
    if (!calibration.hasEnoughData) lines.push('- Data still thin: log outcomes when deals close.');
  }
  lines.push('');

  // Silence ROI
  const impact = buildFollowUpImpact({
    activities: input.activities,
    opportunities: input.opportunities,
    opportunityOutcomes: input.opportunityOutcomes,
    today: input.today,
  });
  lines.push('## What follow-ups changed (last 30 days)');
  lines.push('');
  if (impact.followUpsSent === 0) {
    lines.push('- No follow-ups logged - use "Log as sent" so rescues become measurable.');
  } else {
    const backInMotion = impact.dealsRevived + impact.dealsWon + impact.dealsProtected;
    lines.push(`- ${impact.followUpsSent} follow-ups sent, ${impact.quietDealsContacted} to quiet deals; ${backInMotion} back in motion worth ${formatBaseCurrencyAmount(impact.valueBackInMotionBase, true)}.`);
    impact.events.slice(0, 3).forEach((event) => {
      lines.push(`- ${event.accountName} / ${event.opportunityName}: ${followUpImpactStatusLabel(event.status)} - ${event.evidence}`);
    });
  }
  lines.push('');

  // Objection playbook
  const playbook = buildObjectionPlaybook({ objections: input.objections, opportunityOutcomes: input.opportunityOutcomes });
  lines.push('## What worked against objections');
  lines.push('');
  if (playbook.needsMoreData || playbook.insights.length === 0) {
    lines.push('- Not enough objection history yet - log resolution notes when objections close.');
  } else {
    lines.push(`- ${playbook.headline}`);
    playbook.insights.slice(0, 3).forEach((insight) => {
      lines.push(`- ${insight.objectionType} (${formatObjectionResolutionRate(insight)}${insight.dealsLostTo > 0 ? `, cost ${insight.dealsLostTo} ${insight.dealsLostTo === 1 ? 'deal' : 'deals'}` : ''})`);
      insight.provenResponses.slice(0, 2).forEach((response) => lines.push(`  - Proven: ${response}`));
    });
  }
  lines.push('');

  // Outcome patterns
  const learning = analyzePersonalSalesLearning({ outcomes: input.opportunityOutcomes, opportunities: input.opportunities, limit: 3 });
  lines.push('## Outcome patterns');
  lines.push('');
  if (!learning.hasEnoughData) {
    lines.push(`- ${learning.lowDataMessage}.`);
  } else if (learning.insights.length === 0) {
    lines.push('- No repeated pattern detected yet across closed outcomes.');
  } else {
    learning.insights.forEach((insight) => {
      lines.push(`- ${insight.title}: ${insight.pattern} Suggested change: ${insight.suggestedBehaviorChange}`);
    });
  }

  return lines.join('\n').trimEnd();
}
