import type { CrmLiteOpportunity } from '../services/opportunityStore.ts';
import type { OpportunityOutcomeRecord } from '../services/opportunityOutcomeStore.ts';
import type { SalesActivityRecord } from '../services/salesActivityStore.ts';
import { buildFollowUpImpact, followUpImpactStatusLabel } from './followUpImpact.ts';
import { classifyOpportunitySilence } from './proactiveNudges.ts';
import { formatBaseCurrencyAmount } from './money.ts';
import { formatSafeBusinessDate } from './safeDate.ts';

type FollowUpBriefInput = {
  activities: SalesActivityRecord[];
  opportunities: CrmLiteOpportunity[];
  opportunityOutcomes?: OpportunityOutcomeRecord[];
  periodLabel: string;
  today?: string;
};

/**
 * The Follow-up Brief (direction 7.5): one copyable answer to "which deals
 * need a touch now, and did my follow-ups work?". The needs-a-touch list
 * comes from the same silence classifier that powers the nudges; the
 * did-it-work section comes from measured follow-up impact. Nothing here
 * is generated by AI or extrapolated beyond logged touches.
 */
export function generateFollowUpBriefMarkdown(input: FollowUpBriefInput): string {
  const lines: string[] = [
    `# Follow-up Brief - ${input.periodLabel}`,
    '',
    '> Built from captured touches only. Quiet-deal detection uses the same silence rules as the nudges; impact counts only follow-ups you logged as sent.',
    '',
  ];

  // Deals needing a touch now - the action half of the brief.
  const quietDeals = input.opportunities
    .filter((opportunity) => opportunity.status === 'Active')
    .map((opportunity) => ({
      opportunity,
      silence: classifyOpportunitySilence(opportunity, input.activities, input.today),
    }))
    .filter(({ silence }) => silence.status === 'silent' || silence.status === 'at-risk')
    .sort((a, b) => (b.silence.daysQuiet ?? 0) - (a.silence.daysQuiet ?? 0));

  lines.push('## Needs a touch now');
  lines.push('');
  if (quietDeals.length === 0) {
    lines.push('- No active deal is quiet past the silence threshold. Keep capturing touches so this stays true.');
  } else {
    quietDeals.slice(0, 6).forEach(({ opportunity, silence }) => {
      lines.push(`- ${opportunity.accountName || 'Needs confirmation'} / ${opportunity.opportunityName || 'Needs confirmation'}: quiet ${silence.daysQuiet}d (${silence.status === 'silent' ? 'going silent' : 'at risk'})`);
      lines.push(`  - Do next: ${opportunity.nextAction || 'Draft a follow-up and book the next touch.'}`);
    });
  }
  lines.push('');

  // Did the follow-ups work - the evidence half.
  const impact = buildFollowUpImpact({
    activities: input.activities,
    opportunities: input.opportunities,
    opportunityOutcomes: input.opportunityOutcomes,
    today: input.today,
  });
  lines.push(`## What follow-ups changed (last ${impact.windowDays} days)`);
  lines.push('');
  if (impact.followUpsSent === 0) {
    lines.push('- No follow-ups logged - use "Log as sent" so rescues become measurable.');
  } else {
    const backInMotion = impact.dealsRevived + impact.dealsWon + impact.dealsProtected;
    lines.push(`- ${impact.followUpsSent} follow-ups sent, ${impact.quietDealsContacted} to quiet deals; ${backInMotion} back in motion worth ${formatBaseCurrencyAmount(impact.valueBackInMotionBase, true)}.`);
    impact.events.forEach((event) => {
      lines.push(`- ${event.accountName} / ${event.opportunityName}: ${followUpImpactStatusLabel(event.status)} (sent ${formatSafeBusinessDate(event.followUpDate)}${typeof event.daysQuietBefore === 'number' ? ` after ${event.daysQuietBefore}d quiet` : ''})`);
    });
    if (impact.dealsWaiting > 0) {
      lines.push(`- Still waiting on a reply: ${impact.dealsWaiting} ${impact.dealsWaiting === 1 ? 'deal' : 'deals'} - book the next touch instead of waiting passively.`);
    }
  }

  return lines.join('\n').trimEnd();
}
