/**
 * Pulls the three brand faces down from Google Fonts so the app can serve them
 * itself, and writes the `@font-face` block that points at the local copies.
 *
 * Why self-host at all. `src/index.css` opened with
 * `@import url('https://fonts.googleapis.com/...')`, which is the slowest way a
 * page can ask for a font: the browser must fetch the HTML, then the CSS, then
 * discover the import, then fetch a second stylesheet from another origin, then
 * finally the font files - four serial round trips before the first word can be
 * painted in the right typeface. It was also the only third party on the
 * landing page, so an operator on a network that cannot reach `fonts.gstatic.com`
 * got the fallback stack and the CSP had to name two Google hosts.
 *
 * Only three subsets are taken: `latin`, `latin-ext` and `vietnamese`. The
 * interface is English and the records are Vietnamese customer names, so
 * dropping Cyrillic and Greek removes files nobody in this product will render
 * while keeping every character somebody will actually type. `unicode-range` is
 * copied through unchanged, so a browser still downloads only the subset a page
 * needs.
 *
 * Variable fonts, one file per family per subset, so all six Outfit weights and
 * all five Inter weights cost one download rather than eleven.
 *
 * Re-run with `npm run fetch:fonts` when a family or a weight range changes.
 * The output is committed - a build must never depend on Google being up.
 */
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const SUBSETS = new Set(['latin', 'latin-ext', 'vietnamese']);

const FAMILIES = 'family=Outfit:wght@300..800&family=Inter:wght@300..700&family=JetBrains+Mono:wght@400..700';
const CSS_URL = `https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`;

// Google serves woff2 only to a user agent it believes supports it.
const MODERN_UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const FONT_DIR = join(process.cwd(), 'public', 'fonts');
const CSS_OUT = join(process.cwd(), 'src', 'fonts.css');

const css = await fetch(CSS_URL, { headers: { 'User-Agent': MODERN_UA } }).then((res) => {
  if (!res.ok) throw new Error(`Google Fonts CSS returned ${res.status}`);
  return res.text();
});

/** Each block is preceded by a `/* subset *\/` comment, which is the only place the subset is named. */
const blocks = [];
const blockPattern = /\/\* ([a-z-]+) \*\/\s*@font-face \{([^}]+)\}/g;
let match = blockPattern.exec(css);
while (match) {
  blocks.push({ subset: match[1], body: match[2] });
  match = blockPattern.exec(css);
}
if (blocks.length === 0) throw new Error('No @font-face blocks found - the CSS format changed');

const field = (body, name) => {
  const found = new RegExp(`${name}:\\s*([^;]+);`).exec(body);
  return found ? found[1].trim() : '';
};

await mkdir(FONT_DIR, { recursive: true });

const kept = [];
let downloaded = 0;

for (const block of blocks) {
  if (!SUBSETS.has(block.subset)) continue;

  const family = field(block.body, 'font-family').replace(/['"]/g, '');
  const weight = field(block.body, 'font-weight');
  const style = field(block.body, 'font-style') || 'normal';
  const unicodeRange = field(block.body, 'unicode-range');
  const remote = /url\((https:\/\/[^)]+)\)/.exec(block.body)?.[1];
  if (!remote) continue;

  const slug = `${family.toLowerCase().replace(/\s+/g, '-')}-${block.subset}.woff2`;
  const bytes = Buffer.from(await fetch(remote).then((res) => {
    if (!res.ok) throw new Error(`${slug} returned ${res.status}`);
    return res.arrayBuffer();
  }));
  await writeFile(join(FONT_DIR, slug), bytes);
  downloaded += 1;

  kept.push({ family, weight, style, unicodeRange, slug, subset: block.subset, size: bytes.length });
}

const rules = kept.map((font) => `/* ${font.subset} */
@font-face {
  font-family: '${font.family}';
  font-style: ${font.style};
  font-weight: ${font.weight};
  font-display: swap;
  src: url('/fonts/${font.slug}') format('woff2');
  unicode-range: ${font.unicodeRange};
}`).join('\n\n');

const header = `/**
 * Generated by scripts/fetch-fonts.mjs - do not edit by hand.
 *
 * The three brand faces, served from this origin. See the script for why the
 * Google Fonts @import was removed and why only latin, latin-ext and vietnamese
 * are carried.
 *
 * Files live in public/fonts and are fingerprinted by nothing, so they are
 * cached by the service worker's asset rule and re-fetched only when the name
 * changes. Re-run \`npm run fetch:fonts\` to refresh them.
 */

`;

await writeFile(CSS_OUT, `${header}${rules}\n`);

const total = kept.reduce((sum, font) => sum + font.size, 0);
console.log(`Downloaded ${downloaded} font files (${Math.round(total / 1024)} KB) into public/fonts`);
for (const font of kept) {
  console.log(`  ${font.slug.padEnd(34)} ${String(Math.round(font.size / 1024)).padStart(4)} KB  weight ${font.weight}`);
}
console.log(`Wrote ${CSS_OUT}`);
