import {test,before,after} from 'node:test';import assert from 'node:assert/strict';
import {createSupabaseCompatibleDatabase,applyMigrations,productionMigrations,seedAuthUsers,OWNER_A,OWNER_B,setAuthenticatedOwner} from '../../scripts/release-database-harness.mjs';
import {createTrustCapsule} from '../../src/domain/commercialKernel/trustCapsule.ts';
let db,exchange,legacy;const migration='20261001052818_federated_thread_exchanges.sql';
const insert=(database,owner,value=exchange)=>database.query(`INSERT INTO commercial_events(id,user_id,event_type,occurred_at,recorded_at,created_at,summary,structured_payload,idempotency_key,source_type,source_id,thread_id)
 VALUES($1,$2,'federated_thread_issued','2026-10-01T00:00:00Z','2026-10-01T00:00:00Z','2026-10-01T00:00:00Z','Federated thread exchange issued',$3,$1,'manual',$4,'private-thread')`,['federated-thread:'+value.exchangeId,owner,value,value.exchangeId]);
before(async()=>{db=await createSupabaseCompatibleDatabase();const files=productionMigrations();await applyMigrations(db,files.slice(0,files.indexOf(migration)));await seedAuthUsers(db);await setAuthenticatedOwner(db,OWNER_A);await db.query("INSERT INTO commercial_events(id,user_id,event_type,summary) VALUES('legacy',$1,'activity_captured','Existing fact')",[OWNER_A]);legacy=(await db.query("SELECT * FROM commercial_events WHERE id='legacy'")).rows[0];await db.exec('RESET ROLE');await applyMigrations(db,[migration]);await setAuthenticatedOwner(db,OWNER_A);
 const statement={format:'memoire.shared-commitment',version:1,statementId:crypto.randomUUID(),issuedAt:'2026-10-01T00:00:00Z',issuer:{reference:'org-a',label:'Issuer'},recipient:{reference:'org-b',label:'Recipient'},commitmentRef:'PUBLIC-42',promise:{responsiblePerson:'Person',text:'Selected promise',dueDate:null,status:'open',completionEvidence:null},sourceUpdatedAt:'2026-09-01T00:00:00Z',sample:false,authority:{kind:'issuer-declaration',recipientAccepted:false}};
 exchange={format:'memoire.federated-thread',version:1,exchangeId:crypto.randomUUID(),issuedAt:statement.issuedAt,issuer:statement.issuer,recipient:statement.recipient,thread:{reference:'PUBLIC-THREAD',objective:'Delivery outcome'},capsules:[await createTrustCapsule(statement)],sample:false,authority:statement.authority};});
after(async()=>db?.close());
test('populated upgrade preserves prior facts and exchange issuance adds no state revision',async()=>{assert.deepEqual((await db.query("SELECT * FROM commercial_events WHERE id='legacy'")).rows[0],legacy);await insert(db,OWNER_A);assert.equal((await db.query('SELECT count(*)::int n FROM commercial_state_revisions')).rows[0].n,0);});
test('exchange identity/content and client deletion are immutable while replay keeps original time',async()=>{const id='federated-thread:'+exchange.exchangeId,prior=(await db.query('SELECT * FROM commercial_events WHERE id=$1',[id])).rows[0];await db.query('UPDATE commercial_events SET occurred_at=clock_timestamp(),recorded_at=clock_timestamp(),created_at=clock_timestamp() WHERE id=$1',[id]);assert.deepEqual((await db.query('SELECT * FROM commercial_events WHERE id=$1',[id])).rows[0],prior);await assert.rejects(db.query("UPDATE commercial_events SET summary='Changed' WHERE id=$1",[id]),/immutable/);await assert.rejects(db.query('DELETE FROM commercial_events WHERE id=$1',[id]),/cannot be deleted/);});
test('privacy/scope guard refuses extra fields, foreign parties, duplicate statement identity and fake acceptance',async()=>{
 for(const patch of [{privateNote:'Secret'},{recipient:{reference:'third-party',label:'Third'}},{capsules:[...exchange.capsules,...exchange.capsules]},{authority:{kind:'issuer-declaration',recipientAccepted:true}},{sample:true}])await assert.rejects(insert(db,OWNER_A,{...exchange,exchangeId:crypto.randomUUID(),...patch}));
 const changed=structuredClone(exchange);changed.exchangeId=crypto.randomUUID();changed.capsules[0].statement.promise.privateNote='Secret';await assert.rejects(insert(db,OWNER_A,changed));
});
test('existing owner RLS denies other accounts and anonymous access',async()=>{await setAuthenticatedOwner(db,OWNER_B);assert.equal((await db.query('SELECT * FROM commercial_events')).rows.length,0);await assert.rejects(insert(db,OWNER_A,{...exchange,exchangeId:crypto.randomUUID()}),/row-level/);await db.exec('SET ROLE anon');await assert.rejects(db.query('SELECT * FROM commercial_events'),/permission denied/);await setAuthenticatedOwner(db,OWNER_A);});
test('fresh migration chain recovers exchange events idempotently without shared database authority',async()=>{const row=(await db.query('SELECT * FROM commercial_events WHERE id=$1',['federated-thread:'+exchange.exchangeId])).rows[0],target=await createSupabaseCompatibleDatabase();try{await applyMigrations(target);await seedAuthUsers(target);await setAuthenticatedOwner(target,OWNER_A);const columns=Object.keys(row),updates=columns.filter(c=>!['id','user_id'].includes(c)).map(c=>c+'=EXCLUDED.'+c).join(',');const sql='INSERT INTO commercial_events('+columns.join(',')+') VALUES('+columns.map((_,i)=>'$'+(i+1)).join(',')+') ON CONFLICT(user_id,id) DO UPDATE SET '+updates;await target.query(sql,Object.values(row));await target.query(sql,Object.values(row));assert.deepEqual((await target.query('SELECT * FROM commercial_events')).rows,[row]);}finally{await target.close();}});
