import {test,beforeEach} from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){if(['./workspaceDataCache','./cloudJsonCollectionStore','./localWriteGuard'].includes(s))return next(s+'.ts',c);return next(s,c);},load(url,c,next){if(url.endsWith('/services/workspaceDataCache.ts'))return{format:'module',shortCircuit:true,source:'export const invalidateWorkspaceCollection=()=>{};'};if(url.endsWith('/services/cloudJsonCollectionStore.ts'))return{format:'module',shortCircuit:true,source:'export const claimLocalCollectionForUser=()=>true,loadCloudJsonCollection=async()=>[],mergeCloudJsonRecords=(a)=>a,sendOwedCloudJsonRecords=()=>{},syncCloudJsonCollectionForCurrentUser=()=>{globalThis.assetCloudWrites++;},deleteCloudJsonRecordForCurrentUser=()=>{globalThis.assetCloudDeletes++;};'};if(url.endsWith('/lib/supabaseClient.ts'))return{format:'module',shortCircuit:true,source:'export const supabaseClient=null; export const isPipelineSupabaseConfigured=false;'};return next(url,c);}});
class Storage{map=new Map();fail=false;getItem(k){return this.map.get(k)??null;}setItem(k,v){if(this.fail)throw new DOMException('Full','QuotaExceededError');this.map.set(k,String(v));}removeItem(k){this.map.delete(k);}}
const storage=new Storage();globalThis.window={localStorage:storage,dispatchEvent(){}};globalThis.CustomEvent=class{constructor(type){this.type=type;}};
const {createSalesAsset,updateSalesAsset,deleteSalesAsset,saveSalesAssets,loadSalesAssets,emptySalesAssetInput}=await import('../../src/services/salesAssetStore.ts');
const input={...emptySalesAssetInput,title:'Synthetic proof',summary:'Review scope',content:'Synthetic evidence only.'};
beforeEach(()=>{storage.map.clear();storage.fail=false;globalThis.assetCloudWrites=0;globalThis.assetCloudDeletes=0;});
test('asset creation refuses quota failure instead of returning an unsaved record',()=>{storage.fail=true;assert.throws(()=>createSalesAsset(input),/not saved|storage/i);assert.deepEqual(loadSalesAssets(),[]);assert.equal(globalThis.assetCloudWrites,0);});
test('asset edit preserves prior content and rejects an unsaved change',()=>{const original=createSalesAsset(input);storage.fail=true;assert.throws(()=>updateSalesAsset(original,{...input,content:'Revised'}),/not saved|storage/i);assert.equal(loadSalesAssets()[0].content,input.content);});
test('bulk asset import and deletion report a refused local write',()=>{const original=createSalesAsset(input);storage.fail=true;assert.equal(saveSalesAssets([{...original,id:'new'}]),false);assert.equal(deleteSalesAsset(original.id),false);assert.deepEqual(loadSalesAssets().map(r=>r.id),[original.id]);assert.equal(globalThis.assetCloudWrites,1);assert.equal(globalThis.assetCloudDeletes,0);});
